global using System.Diagnostics.CodeAnalysis;
global using System.Net;
global using System.Net.Http.Json;
global using CleanAspCore.Api.Tests.TestSetup;
global using CleanAspCore.Api.TestUtils;
global using CleanAspCore.Api.TestUtils.Fakers;
global using TUnit.Assertions;
global using TUnit.Assertions.Extensions;
global using TUnit.Core;
